import { useState } from "react";
import Head from "next/head";
import { Toggle } from "../components";

export default function Home() {
  const [state, setStart] = useState(true);
  return (
    <>
      <Head>
        <title>Gamify Education settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toggle handleToggle={() => setStart((s) => !s)} checked={state} />
    </>
  );
}
